### ISSUE TITLE
Update jsonld.js version to fix relative remote context bug

### ISSUE THREAD

**Issue by alexkreidler** [rdfjs-base/parser-jsonld#10]
Right now, using `@rdfjs/parser-jsonld` v1.2.1, which depends on `jsonld` 1.8.1, I'm getting the following error:

```
Uncaught jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object.
Possible causes are an inaccessible URL perhaps due to a same-origin policy
(ensure the server uses CORS if you are using client-side JavaScript),
too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.
```

I just tested this with `jsonld` version 3.1.1, and it parses the context perfectly fine. I may open a PR to do this update.

**Comment by alexkreidler** [comment]
Well this may actually be caused by:
https://github.com/rdfjs-base/parser-jsonld/blob/6b200a9286c20ce6c03c83b76186740678964e17/lib/ParserStream.js#L68

Because I have a relative string in my `@context` field, and the calling library, [Alcaeus](https://github.com/wikibus/Alcaeus), doesn't pass the baseIRI properly.

I'll file this issue with them, but I'll leave the issue open as there probably are updates and perf fixes that would be good to update the `jsonld` library for.

**Comment by bergos** [comment]
Looks like this was a problem in the other library. Feel free to reply to this issue if you think it's a problem in this package and please provide a simple example.
