### ISSUE TITLE
Consider using jsonld-streaming-parser

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs-base/parser-jsonld#4]
https://github.com/rubensworks/jsonld-streaming-parser.js

@rubensworks

**Comment by ktk** [comment]
This package is not capable for parsing a JSON-LD file without connection to the internet, due to `jsonld` lib. It tries to load JSON-LD contexts and that obviously fails in offline/intranet without proxy scenarios.

The streaming parser would probably fix that.

**Comment by rubensworks** [comment]
Indeed, the streaming parser can do this using a custom [`documentLoader`](https://github.com/rubensworks/jsonld-context-parser.js#create-a-new-parser).

I would suspect `jsonld` to be capable of injecting local contexts in a similar way as well though.

**Comment by bergos** [comment]
I created a new issue #11 for the loader topic.

**Comment by bergos** [comment]
implemented in #14
